table Data
	lineageTag: 268edf34-f9de-4a38-a392-a55f0eee0279

	column Region
		dataType: string
		lineageTag: 0b70c42b-7ecc-43c5-a79e-b31551af9729
		summarizeBy: none
		sourceColumn: Region
		sortByColumn: IdRegion

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column UnemploymentRate
		dataType: double
		formatString: #,0.0%;-#,0.0%;#,0.0%
		lineageTag: 2d6dcfc7-b7d1-407d-bfe6-b3552464c707
		summarizeBy: sum
		sourceColumn: UnemploymentRate

		annotation SummarizationSetBy = Automatic

	column UnemployedPeople
		dataType: int64
		formatString: 0
		lineageTag: f7c77afd-8f91-476f-a8e9-c1aab45b0190
		summarizeBy: sum
		sourceColumn: UnemployedPeople

		annotation SummarizationSetBy = Automatic

	column IdRegion
		dataType: int64
		formatString: 0
		lineageTag: 6950d3e5-fc78-4e3b-b2c2-29af730299e9
		summarizeBy: sum
		sourceColumn: IdRegion

		annotation SummarizationSetBy = Automatic

	partition Data = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\Klymchuk Dmytriy\Documents\ChatGPT\Пост в LinkedIn\youth-unemployment2026\data\youth-unemployment.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "Data", Kind = "Sheet"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Region", type text}, {"Year", Int64.Type}, {"AgeGroup", type text}, {"UnemploymentRate", type number}, {"UnemployedPeople", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed column type",{"Year", "AgeGroup"}),
				    #"Added Index1" = Table.AddIndexColumn(#"Removed Columns", "Index.1", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index1",{"Index.1", "Region", "UnemploymentRate", "UnemployedPeople"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index.1", "IdRegion"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns","Northern, Southern and Western Europe","North, South & West Europe",Replacer.ReplaceText,{"Region"})
				in
				    #"Replaced Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
